### ISSUE TITLE
Production runs

### ISSUE THREAD

**Issue by hyschive** [yt-project/libyt#18]
### Tasks
- [ ] Test `libyt` in scientific production runs
  - [ ] Cluster merger
  - [x] MW-sized FDM halo
  - [ ] FDM soliton random walk
  - [x] CCSN?
- [ ] What metrics to be collected?
- [ ] Enzo too?

**Comment by cindytsai** [comment]
@hyschive I want to close this issue. (I'm closing `libyt-v0.1` project board.)

**Comment by hyschive** [comment]
@cindytsai Sure
