### ISSUE TITLE
Support Enzo

### ISSUE THREAD

**Issue by hyschive** [yt-project/libyt#4]
### Tasks
- [x] Support libyt in Enzo
- [x] Test on `yt.ParticlePlot` with different `ptype` particles.
- [x] Test ghost zone.
- [ ] Test on face-centered data.
### Notes
- Work with Matt on this

**Comment by cindytsai** [comment]
The face-centered Zeus field is not working, and we will try to fix that in the next libyt release.
